### ISSUE TITLE
team/donor_history.py generates error 500

### ISSUE THREAD

**Issue by alexbueno** [ClodoaldoPinto/KS2#2]
When accessing http://kakaostats.alexbueno.me/team-history?team=XXX or http://kakaostats.alexbueno.me/donor-history?donor=XXX and error 500 is generated by the server.

Weirdly it's not the custom error file as configured in vhost file, and no error message is generated anywhere (vhost log, pgsql log, syslog......)

I also noticed that when DB has just a few summary files imported, both pages load, but without chart. After a few more files imported this error comes out.

**Comment by ClodoaldoPinto** [comment]
Check the configured **error** log file in the host.conf file. In Centos the directory is `/etc/httpd/conf.d/`. The directive is `ErrorLog`

**Comment by alexbueno** [comment]
It's right! 

ErrorLog /var/log/apache2/kakaostats.com-error.log

Also I increased LogLevel to debug, but still... This error isn't showing anywhere.

**Comment by ClodoaldoPinto** [comment]
Did you check the Apache error log? Should be in the same directory.

**Comment by ClodoaldoPinto** [comment]
Add to kakaostats.wsgi

```
import sys, logging
logging.basicConfig(stream=sys.stderr)
```

**Comment by alexbueno** [comment]
About the Apache error log, yes... Since I disabled the defaulf.conf, there's errors related only with service start/stop.

I'm going to add these lines and come back soon!

**Comment by alexbueno** [comment]
Got this error... Trying to understand yet...

```
ERROR:__main__:Exception on /team-history [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1504, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1264, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/kakaostats.com/view/team_history.py", line 128, in team_history
    history_json=history_json
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 123, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 107, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/kakaostats.com/templates/team-history.html", line 1, in top-level template code
    {%- extends "base.html" %}
  File "/var/www/kakaostats.com/templates/base.html", line 16, in top-level template code
    {%- block content %}
  File "/var/www/kakaostats.com/templates/team-history.html", line 39, in block "content"
    {% for i in range(1, group.list[0]['dow']) -%}
TypeError: integer argument expected, got float
```

**Comment by ClodoaldoPinto** [comment]
Try the (untested) fix: https://github.com/ClodoaldoPinto/KS2/commit/4114464e695327e5743f605dd438f3dc4c08d86d

**Comment by alexbueno** [comment]
It worked! Could you do the same for donor page?

**Comment by ClodoaldoPinto** [comment]
You mean the donor_history? Done.

**Comment by ClodoaldoPinto** [comment]
https://github.com/ClodoaldoPinto/KS2/commit/b61d96892254582d4b615ab634e232d9003d4f70

**Comment by alexbueno** [comment]
Thanks! Everything seems to be working fine!
